//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stocktronic.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class STEntities : DbContext
    {
        public STEntities()
            : base("name=STEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PF_CARRITO> PF_CARRITO { get; set; }
        public virtual DbSet<PF_CATEGORIA> PF_CATEGORIA { get; set; }
        public virtual DbSet<PF_DETALLE_ORDEN> PF_DETALLE_ORDEN { get; set; }
        public virtual DbSet<PF_H_ENTREGAS> PF_H_ENTREGAS { get; set; }
        public virtual DbSet<PF_H_ERRORES> PF_H_ERRORES { get; set; }
        public virtual DbSet<PF_INFO_PAGO> PF_INFO_PAGO { get; set; }
        public virtual DbSet<PF_METODO_PAGO> PF_METODO_PAGO { get; set; }
        public virtual DbSet<PF_ORDEN> PF_ORDEN { get; set; }
        public virtual DbSet<PF_PRODUCTO> PF_PRODUCTO { get; set; }
        public virtual DbSet<PF_PROVEEDOR> PF_PROVEEDOR { get; set; }
        public virtual DbSet<PF_ROL> PF_ROL { get; set; }
        public virtual DbSet<PF_SUCURSAL> PF_SUCURSAL { get; set; }
        public virtual DbSet<PF_USUARIO> PF_USUARIO { get; set; }
    }
}
