//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stocktronic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PF_CARRITO
    {
        public long ID_CARRITO { get; set; }
        public long CAR_CANTIDAD { get; set; }
        public long FK_ID_USUARIO { get; set; }
        public long FK_ID_PRODUCTO { get; set; }
    
        public virtual PF_PRODUCTO PF_PRODUCTO { get; set; }
        public virtual PF_USUARIO PF_USUARIO { get; set; }
    }
}
