//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stocktronic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PF_DETALLE_ORDEN
    {
        public long ID_DETALLEORDEN { get; set; }
        public long FK_ID_PRODUCTO { get; set; }
        public decimal DET_PRECIO { get; set; }
        public long DET_CANTIDAD { get; set; }
        public string DET_URL_IMAGEN { get; set; }
        public long FK_ID_ORDEN { get; set; }
        public long FK_ID_USUARIO { get; set; }
    
        public virtual PF_ORDEN PF_ORDEN { get; set; }
    }
}
