//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stocktronic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PF_H_ENTREGAS
    {
        public long ID_ENTREGAS { get; set; }
        public System.DateTime ENT_FEC_ENTREGA { get; set; }
        public long FK_ID_PRODUCTO { get; set; }
        public long FK_ID_PROVEEDOR { get; set; }
    
        public virtual PF_PRODUCTO PF_PRODUCTO { get; set; }
        public virtual PF_PROVEEDOR PF_PROVEEDOR { get; set; }
    }
}
