//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stocktronic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PF_INFO_PAGO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PF_INFO_PAGO()
        {
            this.PF_ORDEN = new HashSet<PF_ORDEN>();
        }
    
        public long ID_INFOPAGO { get; set; }
        public string PAG_NUM_TARJETA { get; set; }
        public string PAG_DIR_FACTURACION { get; set; }
        public string PAG_DIR_FACTURACION2 { get; set; }
        public string PAG_TELEFONO { get; set; }
        public decimal PAG_TOTAL { get; set; }
        public long FK_ID_USUARIO { get; set; }
        public long FK_ID_METODOPAGO { get; set; }
    
        public virtual PF_METODO_PAGO PF_METODO_PAGO { get; set; }
        public virtual PF_USUARIO PF_USUARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PF_ORDEN> PF_ORDEN { get; set; }
    }
}
