//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stocktronic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PF_ORDEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PF_ORDEN()
        {
            this.PF_DETALLE_ORDEN = new HashSet<PF_DETALLE_ORDEN>();
        }
    
        public long ID_ORDEN { get; set; }
        public System.DateTime ORD_FEC_ORDEN { get; set; }
        public decimal ORD_MONTO_TOTAL { get; set; }
        public long FK_ID_INFOPAGO { get; set; }
        public long FK_ID_USUARIO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PF_DETALLE_ORDEN> PF_DETALLE_ORDEN { get; set; }
        public virtual PF_INFO_PAGO PF_INFO_PAGO { get; set; }
        public virtual PF_USUARIO PF_USUARIO { get; set; }
    }
}
