//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stocktronic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PF_PRODUCTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PF_PRODUCTO()
        {
            this.PF_CARRITO = new HashSet<PF_CARRITO>();
            this.PF_H_ENTREGAS = new HashSet<PF_H_ENTREGAS>();
        }
    
        public long ID_PRODUCTO { get; set; }
        public string PRO_NOMBRE { get; set; }
        public string PRO_DESCRIPCION { get; set; }
        public string PRO_URL_IMAGEN { get; set; }
        public decimal PRO_PRECIO { get; set; }
        public long PRO_CANTIDAD { get; set; }
        public long FK_ID_PROVEEDOR { get; set; }
        public long FK_ID_CATEGORIA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PF_CARRITO> PF_CARRITO { get; set; }
        public virtual PF_CATEGORIA PF_CATEGORIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PF_H_ENTREGAS> PF_H_ENTREGAS { get; set; }
        public virtual PF_PROVEEDOR PF_PROVEEDOR { get; set; }
    }
}
