//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stocktronic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PF_USUARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PF_USUARIO()
        {
            this.PF_CARRITO = new HashSet<PF_CARRITO>();
            this.PF_H_ERRORES = new HashSet<PF_H_ERRORES>();
            this.PF_INFO_PAGO = new HashSet<PF_INFO_PAGO>();
            this.PF_ORDEN = new HashSet<PF_ORDEN>();
        }
    
        public long ID_USUARIO { get; set; }
        public string USR_NOMBRE { get; set; }
        public string USR_APELLIDO1 { get; set; }
        public string USR_APELLIDO2 { get; set; }
        public string USR_EMAIL { get; set; }
        public string USR_PASSWORD { get; set; }
        public long FK_ID_ROL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PF_CARRITO> PF_CARRITO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PF_H_ERRORES> PF_H_ERRORES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PF_INFO_PAGO> PF_INFO_PAGO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PF_ORDEN> PF_ORDEN { get; set; }
        public virtual PF_ROL PF_ROL { get; set; }
    }
}
